language: node_js

node_js:
  - 8
  - 9

services:
  - mysql

before_install:
  - cat sampledb/qm.sql | mysql

before_script:
  - npm install -g coveralls

script:
  - npm test
  - npm run report-coverage
